#include "pomp_lib.h"

struct ompregdescr omp_rd_67 = {
  "region", "traverse_faster", 0, "sparseSA.cpp", 223, 223, 268, 268
};

struct ompregdescr omp_rd_68 = {
  "region", "top_down_child", 0, "sparseSA.cpp", 275, 275, 310, 310
};

struct ompregdescr omp_rd_69 = {
  "region", "loop", 0, "sparseSA.cpp", 577, 577, 612, 612
};

struct ompregdescr omp_rd_70 = {
  "region", "suffixlink", 0, "sparseSA.cpp", 601, 601, 607, 607
};

struct ompregdescr omp_rd_71 = {
  "region", "MUMParallel", 0, "sparseSA.cpp", 678, 678, 727, 727
};

struct ompregdescr omp_rd_72 = {
  "parallel", "", 0, "sparseSA.cpp", 679, 679, 691, 691
};

#define POMP_DLIST_00072 shared(omp_rd_72,omp_rd_73,omp_rd_74)

struct ompregdescr omp_rd_73 = {
  "for", "", 0, "sparseSA.cpp", 681, 681, 686, 686
};

struct ompregdescr omp_rd_74 = {
  "critical", "", 0, "sparseSA.cpp", 687, 687, 690, 690
};

